export const LOADING_TEXT: string[] = [
  'Loading',
  'Mogu Mogu',
  'Finding Love for 298 Yen',
  'Sending Superchat',
  'Learning Explosion Magic',
  'Purging Aberrations',
  'Creating Universe',
  'Pursuing Antartica',
  'Brewing Coffee',
  'Cooking Noodles',
  'Wrapping Onigiri',
  'Assembling Circus',
  'Farming Artifacts',
  'Grinding Charts',
  'Pulling Gacha',
  'Forming Idol Group',
  'Buying Merch',
  'Coding Website',
  'Flipping Record',
  'Peace Peace',
  'Setting Fastest Lap',
  'Ganking Mid',
  'Spinning Leek',
]
