export const SET_PORTFOLIO_LANDING_REF = 'SET_PORTFOLIO_LANDING_REF'
export const SET_PORTFOLIO_DEV_REF = 'SET_PORTFOLIO_DEV_REF'
export const SET_PORTFOLIO_MANAGER_REF = 'SET_PORTFOLIO_MANAGER_REF'
export const SET_PORTFOLIO_JOURNEY_REF = 'SET_PORTFOLIO_JOURNEY_REF'
export const SET_PORTFOLIO_HIGHLIGHTS_REF = 'SET_PORTFOLIO_HIGHLIGHTS_REF'
export const SET_PORTFOLIO_WEB3_REF = 'SET_PORTFOLIO_WEB3_REF'
export const SET_PORTFOLIO_CONTACTS_REF = 'SET_PORTFOLIO_CONTACTS_REF'

// generic one
export const SET_PORTFOLIO_SECTION_REF = 'SET_PORTFOLIO_SECTION_REF'

// current sections
export const SET_CURR_PORTFOLIO_SECTION = 'SET_CURR_PORTFOLIO_SECTION'
export const LEAVE_CURR_PORTFOLIO_SECTION = 'LEAVE_CURR_PORTFOLIO_SECTION'
