name: gh-pages ci

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: node.js setup for deploy
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          user.name: 'breaddog'
          password: ${{secrets.GITHUB_TOKEN}}
      - run: yarn --frozen-lockfile
      - run: yarn deploy
