name: gh-pages ci

on:
  push:
    branches: [main]

env:
  REACT_APP_IS_PROD: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: setup credentials for gh-pages
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: set user.name
        run: git config --global user.name "${{github.actor}}"

      - name: fetch files from repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: install dependencies
        run: yarn

      - name: deploy gh-pages
        run: yarn deploy
